### ISSUE TITLE
Error while git checkout bzip2

### ISSUE THREAD

**Issue by bf-eds** [barndawgie/ffmpeg-cross-compile-script#1]
Hi
I used your script on docker with ubuntu 20.10
And there is error in git checkout - "fatal: 'bzip2-1_0_8' is not a commit and a branch 'release' cannot be created from it".
So i tried:
`bzip2_git="git://sourceware.org/git/bzip2.git"` 
`bzip2_release="bzip2-1.0.8"`
And it helped. 
Thx for your repo, helped me a lot at my work.

**Comment by barndawgie** [comment]
Sorry I missed this bug! I think any issues are here are resolved now...
