### ISSUE TITLE
libopus support for AV1

### ISSUE THREAD

**Issue by Aleksid1** [barndawgie/ffmpeg-cross-compile-script#16]
I recommend to add libopus support which can be used together with AV1 to create a video/audio using only open source patents free codecs. I guess that we need to add something like this?

```
opus_git="https://github.com/xiph/opus.git"
opus_release="v1.4"
```

`--enable-libopus \`

```
# opus: Audio Codec
do_git_checkout $opus_git $opus_release opus
pushd opus || exit
./configure $configure_params
make -j $threads
make install
popd || exit
```

**Comment by barndawgie** [comment]
Do you know how to submit a PR?

**Comment by Aleksid1** [comment]
Not yet. Sorry!
I just tried to compile the script with my addition (libopus) and it failed (pkg-config cannot find libopus).

**Comment by barndawgie** [comment]
Try adding autogen.sh:
```bash
    do_git_checkout $opus_git $opus_release opus
    pushd opus || exit
    ./autogen.sh $configure_params
    ./configure $configure_params
    make -j $threads
    make install
    popd || exit
 ```

**Comment by barndawgie** [comment]
https://github.com/barndawgie/ffmpeg-cross-compile-script/pull/17 has this change - I'm letting it run a build now to validate

**Comment by Aleksid1** [comment]
Hi, libopus now compiles correctly. Thanks!

**Comment by barndawgie** [comment]
Glad I could help!
