### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by 0Ky** [barndawgie/ffmpeg-cross-compile-script#2]
Compile error `ERROR: libass >= 0.11.0 not found using pkg-config`

Trying to compile in `Ubuntu 22.04.2 LTS` using WLS2.

```
+ pushd ffmpeg
~/ffmpeg-cross-compile-script/packages/ffmpeg ~/ffmpeg-cross-compile-script/packages ~/ffmpeg-cross-compile-script
+ ./configure --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --prefix=/home/user/ffmpeg-cross-compile-script/ffmpeg_install '--extra-libs=-lstdc++ -lbz2' '--extra-cflags=-static-libgcc -static-libstdc++ -static -O3 -s -I/home/user/ffmpeg-cross-compile-script/ffmpeg_install/include' '--extra-cxxflags=-static-libgcc -static-libstdc++ -static -O3 -s' '--extra-ldflags=-static-libgcc -static-libstdc++ -static -O3 -s -L/home/user/ffmpeg-cross-compile-script/ffmpeg_install/lib' '--extra-ldexeflags=-static-libgcc -static-libstdc++ -static -O3 -s' '--extra-ldsoflags=-static-libgcc -static-libstdc++ -static -O3 -s' --logfile=./config.log --enable-nonfree --enable-gpl --enable-libfdk-aac --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libopenjpeg --enable-libaom --enable-nvdec --enable-nvenc --enable-libmp3lame --enable-openssl --enable-libfreetype --enable-libfribidi --enable-libass --enable-libfontconfig --enable-libsrt --enable-libzimg --enable-libmfx --enable-libbluray
ERROR: libass >= 0.11.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "./config.log" produced by configure as this will help
solve the problem.
+ make -j 1
Makefile:184: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
+ make install
Makefile:184: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
+ make -j 1 alltools
Makefile:184: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
+ mkdir -p /home/user/ffmpeg-cross-compile-script/ffmpeg_install/bin/tools/
+ cp './tools/*.exe' /home/user/ffmpeg-cross-compile-script/ffmpeg_install/bin/tools/
cp: cannot stat './tools/*.exe': No such file or directory
+ popd
~/ffmpeg-cross-compile-script/packages ~/ffmpeg-cross-compile-script
+ popd
~/ffmpeg-cross-compile-script
+ echo 'If successful, executables now available at /home/user/ffmpeg-cross-compile-script/ffmpeg_install/bin'
If successful, executables now available at /home/user/ffmpeg-cross-compile-script/ffmpeg_install/bin

~/ffmpeg-cross-compile-script$
```

**Comment by barndawgie** [comment]
Hmmm...repros for me too. Not sure if something changed or what - I will see if I can sort this out.

**Comment by 0Ky** [comment]
Thanks!

Do you think it's related to the Libass\\[Makefile.am](https://github.com/libass/libass/blob/0.14.0/Makefile.am#L5) file?
Should we define `--libdir` in configure? Assuming `pkg-config` can't find `libass.pc` in `$(pwd)/ffmpeg_install/lib/pkgconfig` based on the `ERROR: libass >= 0.11.0 not found using pkg-config`.

**Comment by 0Ky** [comment]
I don't think it's related, but why is there a hard-coded absolute path here [patches/bzip2.pc](https://github.com/barndawgie/ffmpeg-cross-compile-script/blob/89068be/patches/bzip2.pc#L1)?

**Comment by barndawgie** [comment]
> I don't think it's related, but why is there a hard-coded absolute path here [patches/bzip2.pc](https://github.com/barndawgie/ffmpeg-cross-compile-script/blob/89068be/patches/bzip2.pc#L1)?

haha the things you find when someone else actually looks at your work! :-) I'm testing a fix for that.

**Comment by barndawgie** [comment]
I believe I've fixed (well, worked around) the initial error by disabling the harfbuzz dependency. Something has changed and Harfbuzz won't build. These subtitles libraries have an insanely complex dependency chain with circular dependencies and other nonsense that make it really hard to get them building.

Can you check whether this fix worked for you? https://github.com/barndawgie/ffmpeg-cross-compile-script/commit/e7c3e2dd43d4c36be00776d50b518cd8f1784fa3

**Comment by 0Ky** [comment]
> disabling the harfbuzz dependency

Aw, I hope we could eventually get it to compile with it, maybe you can have a look at how other [build scripts](https://github.com/rdp/ffmpeg-windows-build-helpers/blob/7c3f54f/cross_compile_ffmpeg.sh#L1003-L1036) do it?


> Can you check whether this fix worked for you? [e7c3e2d](https://github.com/barndawgie/ffmpeg-cross-compile-script/commit/e7c3e2dd43d4c36be00776d50b518cd8f1784fa3)

Sure, compiling is in progress.

**Comment by 0Ky** [comment]
Great, it builds ffmpeg.exe just fine now.

**Comment by barndawgie** [comment]
Yes, I need to dig more into that. You can see that in the ffmpeg-windows-build-helpers they are having to modify the pkg-config files since they aren't correct for various reasons. I need to explore that.

That said, there seems to be some other change/issue here as the thing that broke was missing glibc2.0; this also broke Intel QuickSync which I had to disable as well. I'm not sure what changed or why that was present on my other machine. I may need to add that to the script but that implies its own dependencies...

**Comment by barndawgie** [comment]
Anyway, I am resolving this issue since it seems it was fixed by https://github.com/barndawgie/ffmpeg-cross-compile-script/commit/e7c3e2dd43d4c36be00776d50b518cd8f1784fa3
