### ISSUE TITLE
How to custom build ffmpeg with this script?

### ISSUE THREAD

**Issue by Usulyre** [barndawgie/ffmpeg-cross-compile-script#4]
Is there a way to custom build any ffmpeg fork with this script?

I would like to build this version here it has a certain feature that I would like to try out.

https://github.com/philipl/FFmpeg/tree/fruc-me

https://github.com/philipl/FFmpeg/commit/e909efd8f85628f423ea21f79a4bd6d696627ef4

**Comment by barndawgie** [comment]
You should be able to just modify the FFmpeg repo location and ref in the definitions near the top of the file.

**Comment by Usulyre** [comment]
Does it matter if it is a different ffmpeg version i think it's older than the one from your script?

**Comment by barndawgie** [comment]
Only way to be sure is to try. I will say I've found the build is much more sensitive to versions of some of the dependencies (which often introduce breaking changes around their own builds/dependencies) than with FFmpeg itself, which has a pretty stable set of interfaces.

**Comment by Usulyre** [comment]
> Only way to be sure is to try. I will say I've found the build is much more sensitive to versions of some of the dependencies (which often introduce breaking changes around their own builds/dependencies) than with FFmpeg itself, which has a pretty stable set of interfaces.

I've spent sometime trying to get it to compile. Getting some errors however. I removed some ffmpeg options for further compatibility but so far I couldn't get it built.

Did you manage to get it built?

If so, can you provide the modified script you used?

Also, is there a command to use your script and not have to start over completely?

**Comment by barndawgie** [comment]
Sorry for the delay but I just checked in a fix - a repo had moved but I have updated the script to pull it.

I plan to work on getting re-running of the script to work more smoothly.

**Comment by Usulyre** [comment]
> Sorry for the delay but I just checked in a fix - a repo had moved but I have updated the script to pull it.
> 
> I plan to work on getting re-running of the script to work more smoothly.

Hi again,

Does your script incorporate  

https://github.com/philipl/FFmpeg/tree/fruc-me

now? Still looking to try out this filter in it: vf_nvoffruc
